from __future__ import annotations
import logging
from typing import Optional

from transformers import pipeline, Pipeline

from config import config
from utils.user_profile import UserProfile, get_feedback_instruction

logger = logging.getLogger(__name__)  

# ── Lazy singleton ─────────────────────────────────────────────────
_critic_pipeline: Optional[Pipeline] = None


def _get_pipeline() -> Pipeline:
    """
    Load the critic LLM once.
    Uses CRITIC_MODEL from .env (e.g. google/flan-t5-large)
    """
    global _critic_pipeline
    if _critic_pipeline is None:
        logger.info(f"Loading critic model: {config.CRITIC_MODEL}")
        _critic_pipeline = pipeline(
            task="summarization",
            model=config.CRITIC_MODEL,
            tokenizer=config.CRITIC_MODEL,
            device=0 if _cuda_available() else -1,
        )
        logger.info("Critic model loaded successfully.")
    return _critic_pipeline


# ── Public API ─────────────────────────────────────────────────────

def critique_summary(
    original_text: str,
    user_profile: UserProfile,
    initial_summary: str,
) -> str:
    """
    Evaluate the initial summary against the original text and user profile.
    Returns actionable critique instructions for the second-pass summarizer.

    Args:
        original_text:   The preprocessed English input from the user.
        user_profile:    The user's profile (level, style, length preference).
        initial_summary: The first-pass summary generated by the summarizer.

    Returns:
        A critique string describing what needs to be improved.
        This string is injected into the second-pass summarizer prompt.
    """
    prompt = _build_critique_prompt(original_text, user_profile, initial_summary)   

    logger.info("Critic agent evaluating initial summary.")
    result = _get_pipeline()(
        prompt,
        max_new_tokens=config.CRITIC_MAX_NEW_TOKENS,
        do_sample=True,
        temperature=config.CRITIC_TEMPERATURE,
        truncation=True,
    )

    critique = result[0]["summary_text"].strip()
    logger.info(f"Critic produced feedback: {critique[:100]}...")
    return (
        f"The summary should be {user_profile.summary_length} length, "
        f"written for a {user_profile.knowledge_level} audience, "
        f"in a {user_profile.summary_style} style. "
        f"Make sure all key points from the original text are covered."
    )


# ── Internal prompt builder ────────────────────────────────────────

def _build_critique_prompt(
    original_text: str,
    profile: UserProfile,
    summary: str,
) -> str:
    """
    Construct a detailed critique prompt for the critic LLM.

    The prompt tells the model:
      - Who the user is (knowledge level, style, length)
      - What the original document contains
      - What the current summary says
      - What to check and report

    We also inject any historical user feedback to make the critic adaptive.
    """
    feedback_instruction = get_feedback_instruction(profile)

    # Truncate original text to avoid exceeding context window
    max_original_chars = 1500
    truncated_original = original_text[:max_original_chars]
    if len(original_text) > max_original_chars:
        truncated_original += "... [truncated]"

    prompt = f"""You are a strict but constructive summary critic.

User profile:
- Knowledge level: {profile.knowledge_level}
- Summary style: {profile.summary_style}
- Summary length: {profile.summary_length}
- Domain: {profile.domain}
{f"- Past feedback context: {feedback_instruction}" if feedback_instruction else ""}

Original document (excerpt):
{truncated_original}

Current summary:
{summary}

Critique instructions:
1. Does the summary match the user's knowledge level ({profile.knowledge_level})? Is the language appropriate?
2. Is the tone and style correct ({profile.summary_style})?
3. Is the length appropriate for the requested {profile.summary_length} summary?
4. Are the most important facts and key points from the original text included?
5. Are there any factual errors or misleading statements compared to the original?

Write a short, specific critique (2-4 sentences) describing what should be improved in the next version of the summary. Be direct and actionable."""

    return prompt


# ── Internal helpers ───────────────────────────────────────────────

def _cuda_available() -> bool:
    try:
        import torch
        return torch.cuda.is_available()
    except ImportError:
        return False