from __future__ import annotations
import logging
from typing import Optional

from transformers import pipeline, Pipeline

from config import config

logger = logging.getLogger(__name__)

# ── Lazy singleton ─────────────────────────────────────────────────
_summarizer_pipeline: Optional[Pipeline] = None


def _get_pipeline() -> Pipeline:
    """
    Load the summarization pipeline once and reuse it.
    Uses the model specified in SUMMARIZER_MODEL in .env
    """
    global _summarizer_pipeline
    if _summarizer_pipeline is None:
        logger.info(f"Loading summarization model: {config.SUMMARIZER_MODEL}")
        _summarizer_pipeline = pipeline(
            task="summarization",
            model=config.SUMMARIZER_MODEL,
            tokenizer=config.SUMMARIZER_MODEL,
            # Use GPU if available, otherwise CPU
            device=0 if _cuda_available() else -1,
        )
        logger.info("Summarization model loaded successfully.")
    return _summarizer_pipeline


# ── Public API ─────────────────────────────────────────────────────

def generate_summary(
    cleaned_text: str,
    personalization_instruction: str,
    summary_length: str = "medium",
) -> str:
    """
    First-pass summarization.
    Combines the personalization instruction with the input text
    and generates an initial English summary.

    Args:
        cleaned_text:                 Preprocessed English input.
        personalization_instruction:  Generated by user_profile.get_personalization_instruction()
        summary_length:               "short" | "medium" | "long"

    Returns:
        Initial English summary string.
    """
    max_len = config.MAX_SUMMARY_LENGTH.get(summary_length, 150)
    min_len = config.MIN_SUMMARY_LENGTH

    # Prepend a clear instruction for the model
    prompt = _build_prompt(cleaned_text, personalization_instruction)

    logger.info(f"Generating first-pass summary (max_length={max_len})")
    result = _get_pipeline()(
        prompt,
        max_length=max_len,
        min_length=min_len,
        do_sample=False,
        truncation=True,
        clean_up_tokenization_spaces=True,
    )

    summary = result[0]["summary_text"].strip()
    logger.info(f"First-pass summary generated ({len(summary.split())} words).")
    return summary


def generate_refined_summary(
    cleaned_text: str,
    personalization_instruction: str,
    critic_feedback: str,
    summary_length: str = "medium",
) -> str:
    """
    Second-pass summarization incorporating critic agent feedback.

    Args:
        cleaned_text:                 Original preprocessed English input.
        personalization_instruction:  Same as first pass.
        critic_feedback:              String produced by the critic agent.
        summary_length:               "short" | "medium" | "long"

    Returns:
        Final refined English summary string.
    """
    max_len = config.MAX_SUMMARY_LENGTH.get(summary_length, 150)
    min_len = config.MIN_SUMMARY_LENGTH

    # Extend the prompt with critic feedback
    prompt = _build_refined_prompt(cleaned_text, personalization_instruction, critic_feedback)

    logger.info(f"Generating second-pass (refined) summary (max_length={max_len})")
    result = _get_pipeline()(
        prompt,
        max_length=max_len,
        min_length=min_len,
        do_sample=False,
        truncation=True,
    )

    refined = result[0]["summary_text"].strip()
    logger.info(f"Refined summary generated ({len(refined.split())} words).")
    return refined


# ── Internal helpers ───────────────────────────────────────────────

def _build_prompt(text: str, instruction: str) -> str:
    # bart-large-cnn only needs the raw text
    # trim to 1024 tokens worth of characters to avoid overflow
    return text[:3000]


def _build_refined_prompt(text: str, instruction: str, critic_feedback: str) -> str:
    # same — just pass raw text, bart ignores instructions anyway
    return text[:3000]


def _cuda_available() -> bool:
    try:
        import torch
        return torch.cuda.is_available()
    except ImportError:
        return False